			</div>
			<div id="footer">
                This testing environment is provided as is. We do not provide any warranty and can not be held responsible for any loss or dommage caused by this script.<br />
                Keep in mind that simulation should NEVER be used in a PRODUCTION environment or on a public webserver. For more information about suggested setup refer to our website.
                <br /><br />
				<p>
					v<?php echo SIM_VERSION; ?> &minus; Copyright &copy; <?php echo YEAR.' &minus; <a href="'.URL.'" target="_blank">'.DISPLAY_URL.'</a>'; ?>
				</p>
			</div>
		</div>
        

	</body>
</html>